'\" t
.\"     Title: yaourtrc
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 2010-04-11
.\"    Manual: Yaourt Manual
.\"    Source: Yaourt 0.9.4
.\"  Language: English
.\"
.TH "YAOURTRC" "5" "2010\-04\-11" "Yaourt 0\&.9\&.4" "Yaourt Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
yaourtrc \- yaourt configuration file
.SH "SYNOPSIS"
.sp
/etc/yaourtrc
.sp
\fB$HOME\fR/yaourtrc
.SH "DESCRIPTION"
.sp
\fByaourt\fR(8) obtains configuration data from the following sources in the following order:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
command\-line options
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
user\(cqs configuration file ($HOME/\&.yaourtrc)
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
system\-wide configuration file (/etc/yaourtrc)
.RE
.SH "OPTIONS"
.PP
\fBABS_REPO=(testing core extra community-testing community gnome-unstable kde-unstable)\fR
.RS 4
List of repositories where PKGBUILD can be retreived by rsync, see /etc/abs.conf\&.
.RE
.PP
\fBAURUPGRADE=0\fR
.RS 4
If set to 1, always search for new version of packages installed from AUR Unsupported when upgrading (yaourt \-Su)\&.
.RE
.PP
\fBAURUPGRADECONFIRM=1\fR
.RS 4
If set to 0, do not prompt for aur upgrades\&.
.RE
.PP
\fBDETAILUPGRADE=1\fR
.RS 4
If set to 0, do not detail updates (new version, release, packages)\&.
.RE
.PP
\fBAURDEVELONLY=0\fR
.RS 4
If set to 1, search only for new version of foreign developpement CVS/SVN packages when upgrading (yaourt \-Su \--devel)\&.
.RE
.PP
\fBDEVEL=0\fR
.RS 4
If set to 1, always search for new version of developpement CVS/SVN packages when upgrading (yaourt \-Su)\&.
.RE
.PP
\fBDEVELBUILDDIR=/var/abs/local/yaourtbuild/\fR
.RS 4
Specify directory where to clone, build devel packages\&.
.RE
.PP
\fBFORCE=0\fR
.RS 4
If set to 1, always bypass file conflict checks and overwrite conflicting files\&.
.RE
.PP
\fBAURVOTE=1\fR
.RS 4
If set to 0, don\(cqt check the vote status for inclusion/keeping in [community], and it is unable to vote\&.
.RE
.PP
\fBAUTOSAVEBACKUPFILE=0\fR
.RS 4
If set to 1, after each install, yaourt search for config files to backup (\&.pacnew files)\&. It store all files in /var/lib/yaourt/\&. These files will be used later with yaourt \-C to automerge current config files with new config files (\&.pacnew)\&.
.RE
.sp
This option requires root password or sudo configured to allow runing /usr/bin/pacdiffviewer without password\&.
.PP
\fBCOLORMODE="normal"\fR
.RS 4
Define the color style to use\&. COLORMODE can be "normal", "lightbg", "nocolor" or "textonly"\&.
.RE
.sp
Note: nocolor use Bold and Italic fonts\&. textonly remove all special caracters and acts like TERMINALTITLE=0
.PP
\fBNOENTER=1\fR
.RS 4
If set to 0, user needs to press Enter for each "yes/no" question\&.
.RE
.PP
\fBEDITFILES=1\fR
.RS 4
If set to 0, don\(cqt propose to edit files (from AUR or from ABS)\&.
.RE
.PP
\fBEXPORTDIR=""\fR
.RS 4
Specify the folder where yaourt export built packages for local repository. This option export \&.pkg\&.tar\&.gz + PKGBUILD + local sources files\&.
.RE
.PP
\fBFORCEENGLISH=0\fR
.RS 4
If set to 1, yaourt use English for makepkg and pacman instead of system language\&.
.RE
.PP
\fBMAXCOMMENTS=X\fR
.RS 4
Show X last comments for packages built from AUR Unsupported\&. default: MAXCOMMENTS=5
.RE
.PP
\fBNOCONFIRM=0\fR
.RS 4
If set to 1, always use the default choice without confirmation\&.
.RE
.PP
\fBPACMANBIN="/usr/bin/pacman"\fR
.RS 4
Specify the pacman binary to use with yaourt
.RE
.PP
\fBEDITOR="$EDITOR"\fR
.RS 4
Define the editor to use (if the environment variable $EDITOR is not set) for PKGBUILD editing\&. Editor should not fork, for gvim: EDITOR="gvim \-\-nofork"
.RE
.PP
\fBAURSEARCH=1\fR
.RS 4
If set to 0, don\(cqt search for packages on AUR Unsupported
.RE
.PP
\fBSHOWORPHANS=1\fR
.RS 4
If set to 0, don\(cqt search for orphans
.RE
.PP
\fBTMPDIR="/tmp"\fR
.RS 4
Specify the folder to save tempory files (default is /tmp)\&.
.RE
.PP
\fBTERMINALTITLE=1\fR
.RS 4
If set to 0, don\(cqt show the current yaourt\(cqs action in terminal title\&. By default, yaourt show messages like "Installing xxx from AUR"\&. It\(cqs recommended to add something like this in your \&.bashrc
.sp
.if n \{\
.RS 4
.\}
.nf
example: PROMPT_COMMAND=\'echo \-ne "\e\e033]0;${USER}@${HOSTNAME}: ${PWD}\e\e007"\'
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBDIFFEDITCMD="vimdiff"\fR
.RS 4
Define the diff editor to use ($DIFFEDITCMD file1 file2)\&.
.RE
.RE
.PP
\fBSUDONOVERIF=0\fR
.RS 4
If set to 1, yaourt doesn\(cqt do sudo checks\&. (For users with timestamp_timeout=0 in sudoers)
.RE
.SH "SEE ALSO"
.sp
\fByaourt\fR(8)
.sp
See the yaourt website at http://archlinux\&.fr/yaourt\-en/ for more info\&.
.SH "BUGS"
.sp
http://bugs\&.archlinux\&.fr
.SH "AUTHORS"
.sp
Current maintainers:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Julien MISCHKOWITZ <wain@archlinux\&.fr>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Tuxce <tuxce\&.net@gmail\&.com>
.RE
